version: "3"
services:
  web:
    build: .
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./:/home/app
  db:
    image: mysql/mysql-server:8.0
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: selfremind
      MYSQL_USER: selfremind
      MYSQL_PASSWORD: selfremind123